title: Caio Pedro Castro # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc. Economics Candidate @ University of São Paulo
  <br><br>
  Data analysis, econometrics, microeconomics 
   <br><br>
  <a href="https://drive.google.com/file/d/1w77CNBKQNnhHM-6PKPj5JIriGaih04iL/view?usp=sharing">CV</a> 
  <br>
  <a href="https://www.linkedin.com/in/caiopasc/">View My LinkedIn Profile</a> 
  
  
  
  
#theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
